import 'dart:io';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import '../data/schemas.dart';

class DBService {
  // Singleton pattern
  static final DBService _instance = DBService._internal();
  factory DBService() => _instance;
  DBService._internal();

  // Single database instance
  static Isar? _db;
  Future<Isar> get db async {
    if (_db != null) return _db!;
    _db = await openDB();
    return _db!;
  }

  // 1. Initialize the Database - Only opens once
  static Future<Isar>? _initFuture;

  Future<Isar> openDB() async {
    if (_db != null) return _db!;
    _initFuture ??= _performOpenDB();
    return _initFuture!;
  }

  Future<Isar> _performOpenDB() async {
    if (_db != null) return _db!;

    if (Isar.instanceNames.isEmpty) {
      final docDir = await getApplicationDocumentsDirectory();
      final dir = Directory('${docDir.path}/SimpleMusicDB');

      if (!await dir.exists()) {
        await dir.create(recursive: true);
      }

      _db = await Isar.open(
        [
          SongSchema,
          PlaylistSchema,
          HistoryEntrySchema,
          SavedStatSchema,
          MailboxMessageSchema,
          DeletedMailboxMessageSchema,
          OnlineArtCacheSchema,
          OnlineDataCacheSchema,
        ], // Register schemas here
        directory: dir.path,
        inspector: true, // Allows you to debug DB content while app runs!
      );
      return _db!;
    }
    _db = Isar.getInstance();
    return _db!;
  }

  // 2. Save Scanned Songs (The "Scanner" Logic)
  // This is smart: It updates existing songs instead of duplicating them.
  // 2. Save Scanned Songs (The "Scanner" Logic)
  // This is smart: It updates existing songs instead of duplicating them.
  Future<void> saveSongs(List<Song> newSongs) async {
    final isar = await db;

    // Using a Transaction (Txn) ensures all data is saved safely at once.
    await isar.writeTxn(() async {
      for (final newSong in newSongs) {
        // 🚀 Canonicalize path for consistent matching (especially on Windows)
        final canonicalPath = p.canonicalize(newSong.path);
        newSong.path = canonicalPath;

        // Check if this path already exists
        final existingSong =
            await isar.songs.filter().pathEqualTo(canonicalPath).findFirst();

        if (existingSong != null) {
          // UPDATE: Keep ID, update fields
          existingSong.title = newSong.title;
          existingSong.artist = newSong.artist;
          existingSong.album = newSong.album;
          existingSong.duration = newSong.duration;
          existingSong.year = newSong.year;
          existingSong.trackNumber = newSong.trackNumber;
          existingSong.discNumber = newSong.discNumber;
          existingSong.genre = newSong.genre;
          // Note: We keep existingSong.path as it might have different casing
          // but canonicalize ensures we match it correctly.
          existingSong.path = canonicalPath;

          await isar.songs.put(existingSong);
        } else {
          // INSERT: New song
          await isar.songs.put(newSong);
        }
      }
    });
  }

  // 3. Fetch All Songs (For Library Page)
  Future<List<Song>> getAllSongs() async {
    final isar = await db;
    // 'sortByName()' is automatically generated by Isar if you index the name,
    // otherwise we can just use default sorting.
    return await isar.songs.where().findAll();
  }

  // 4. Update Stats (For "History" and "Most Played")
  Future<void> updateSongPlayCount(int songId) async {
    final isar = await db;

    await isar.writeTxn(() async {
      final song = await isar.songs.get(songId);
      if (song != null) {
        song.playCount += 1;
        song.lastPlayed = DateTime.now();
        await isar.songs.put(song);

        // Cloud tracking moved to StatsProvider
      }
    });
  }

  // New helper for PlayerProvider (which uses SongModel, not Isar Song)
  Future<void> updateSongPlayCountByPath(String filePath) async {
    final isar = await db;
    final canonicalPath = p.canonicalize(filePath);

    await isar.writeTxn(() async {
      // Find the song by path (Canonicalized)
      final song =
          await isar.songs.filter().pathEqualTo(canonicalPath).findFirst();

      if (song != null) {
        song.playCount += 1;
        song.lastPlayed = DateTime.now();
        await isar.songs.put(song);
      }
    });
  }

  // 5. Get Top 10 Most Played (For Stats Page)
  Future<List<Song>> getMostPlayed() async {
    final isar = await db;
    // This query is incredibly fast compared to sorting a List in Dart
    return await isar.songs.where().sortByPlayCountDesc().limit(10).findAll();
  }

  // 6. Clean Database (Optional: Remove songs that no longer exist on disk)
  Future<void> cleanMissingSongs(List<String> existingPaths) async {
    final isar = await db;
    // Convert to Set for O(1) lookups
    final pathSet = existingPaths.map((e) => p.canonicalize(e)).toSet();

    await isar.writeTxn(() async {
      final allSongs = await isar.songs.where().findAll();
      final idsToDelete = <int>[];

      for (final song in allSongs) {
        final canonicalPath = p.canonicalize(song.path);
        if (!pathSet.contains(canonicalPath)) {
          idsToDelete.add(song.id);
        }
      }

      if (idsToDelete.isNotEmpty) {
        await isar.songs.deleteAll(idsToDelete);
        print(
            "🧹 DBService: Cleaned ${idsToDelete.length} stale song entries.");
      }
    });
  }

  // 7. Get Total Plays (Across all songs)
  Future<int> getTotalPlays() async {
    final isar = await db;
    // Using property sum is efficient
    return await isar.songs.where().playCountProperty().sum();
  }

  // Get Total Plays from STATS (History of all plays, even streamed)
  Future<int> getTotalStatsPlays() async {
    final isar = await db;
    return await isar.savedStats.where().playCountProperty().sum();
  }

  // 💥 EMERGENCY RECOVERY
  Future<void> recoverFromCorruption() async {
    try {
      if (_db != null && _db!.isOpen) {
        await _db!.close();
      }
      _db = null;
      _initFuture = null;

      final docDir = await getApplicationDocumentsDirectory();
      final dirProp = Directory('${docDir.path}/SimpleMusicDB');
      if (await dirProp.exists()) {
        await dirProp.delete(recursive: true);
        print("💥 DBService: Database deleted/reset due to corruption.");
      }
    } catch (e) {
      print("💥 DBService: Failed to reset database: $e");
    }
  }

  // --- MAILBOX OPERATIONS ---

  /// Adds a new message to the mailbox with deduplication and blacklist check
  Future<void> addMailboxMessage(String message, {String? remoteId, DateTime? timestamp}) async {
    final isar = await db;
    await isar.writeTxn(() async {
      // 1. Deduplication: If remoteId exists in mailbox, don't add again
      if (remoteId != null) {
        final existing = await isar.mailboxMessages.filter().remoteIdEqualTo(remoteId).findFirst();
        if (existing != null) return;

        // 2. Blacklist: If remoteId was previously deleted, don't add again
        final deleted = await isar.deletedMailboxMessages.filter().remoteIdEqualTo(remoteId).findFirst();
        if (deleted != null) return;
      }

      final newMessage = MailboxMessage()
        ..message = message
        ..remoteId = remoteId
        ..timestamp = timestamp ?? DateTime.now()
        ..isRead = false;
      await isar.mailboxMessages.put(newMessage);
      
      // Keep only last 100 messages to prevent DB bloat
      final count = await isar.mailboxMessages.count();
      if (count > 100) {
        final oldest = await isar.mailboxMessages.where().sortByTimestamp().limit(count - 100).findAll();
        await isar.mailboxMessages.deleteAll(oldest.map((e) => e.id).toList());
      }
    });
  }

  /// Fetches all mailbox messages, sorted by newest first
  Future<List<MailboxMessage>> getMailboxMessages() async {
    final isar = await db;
    return await isar.mailboxMessages.where().sortByTimestampDesc().findAll();
  }

  /// Marks a specific message as read
  Future<void> markMessageAsRead(int id) async {
    final isar = await db;
    await isar.writeTxn(() async {
      final message = await isar.mailboxMessages.get(id);
      if (message != null) {
        message.isRead = true;
        await isar.mailboxMessages.put(message);
      }
    });
  }

  /// Deletes a specific message and adds to blacklist
  Future<void> deleteMailboxMessage(int id) async {
    final isar = await db;
    await isar.writeTxn(() async {
      final msg = await isar.mailboxMessages.get(id);
      if (msg != null && msg.remoteId != null) {
        // Add to persistent blacklist
        final deletedEntry = DeletedMailboxMessage()..remoteId = msg.remoteId!;
        await isar.deletedMailboxMessages.put(deletedEntry);
      }
      await isar.mailboxMessages.delete(id);
    });
  }

  /// Clears all messages and adds all remote IDs to blacklist
  Future<void> clearMailbox() async {
    final isar = await db;
    await isar.writeTxn(() async {
      final allMsgs = await isar.mailboxMessages.where().findAll();
      final deletedEntries = allMsgs
          .where((m) => m.remoteId != null)
          .map((m) => DeletedMailboxMessage()..remoteId = m.remoteId!)
          .toList();
      
      if (deletedEntries.isNotEmpty) {
        await isar.deletedMailboxMessages.putAll(deletedEntries);
      }
      
      await isar.mailboxMessages.clear();
    });
  }

  // --- ART CACHE OPERATIONS ---

  Future<String?> getArtCache(String key) async {
    final isar = await db;
    final cached = await isar.onlineArtCaches.filter().keyEqualTo(key).findFirst();
    return cached?.url;
  }

  Future<void> saveArtCache(String key, String url) async {
    final isar = await db;
    await isar.writeTxn(() async {
      final cache = OnlineArtCache()
        ..key = key
        ..url = url
        ..lastUpdated = DateTime.now();
      await isar.onlineArtCaches.put(cache);
    });
  }

  // --- DATA CACHE OPERATIONS (JSON) ---

  Future<String?> getDataCache(String key) async {
    final isar = await db;
    final cached = await isar.onlineDataCaches.filter().keyEqualTo(key).findFirst();
    return cached?.json;
  }

  Future<void> saveDataCache(String key, String json) async {
    final isar = await db;
    await isar.writeTxn(() async {
      final cache = OnlineDataCache()
        ..key = key
        ..json = json
        ..lastUpdated = DateTime.now();
      await isar.onlineDataCaches.put(cache);
    });
  }

  // --- CACHE MANAGEMENT ---

  Future<int> getMetadataCacheCount() async {
    final isar = await db;
    final artCount = await isar.onlineArtCaches.count();
    final dataCount = await isar.onlineDataCaches.count();
    return artCount + dataCount;
  }

  Future<String> getMetadataCacheSize() async {
    final isar = await db;
    int totalBytes = 0;

    // 1. Sum up Isar database strings
    final allData = await isar.onlineDataCaches.where().findAll();
    for (var item in allData) {
      totalBytes += (item.json?.length ?? 0);
    }
    final allArt = await isar.onlineArtCaches.where().findAll();
    for (var item in allArt) {
      totalBytes += (item.url?.length ?? 0);
    }

    // 2. Sum up File System folders
    try {
      final tempDir = await getTemporaryDirectory();
      final folders = ['canvas_cache', 'album_arts'];
      for (var folder in folders) {
        final dir = Directory('${tempDir.path}/$folder');
        if (await dir.exists()) {
          await for (var file in dir.list(recursive: true, followLinks: false)) {
            if (file is File) {
              totalBytes += await file.length();
            }
          }
        }
      }
    } catch (_) {}

    if (totalBytes == 0) return "0.0 KB";
    if (totalBytes < 1024 * 1024) {
      return "${(totalBytes / 1024).toStringAsFixed(1)} KB";
    }
    return "${(totalBytes / (1024 * 1024)).toStringAsFixed(1)} MB";
  }

  Future<void> clearMetadataCache() async {
    final isar = await db;
    
    // 1. Clear Isar Collections
    await isar.writeTxn(() async {
      await isar.onlineArtCaches.clear();
      await isar.onlineDataCaches.clear();
    });

    // 2. Clear File System folders
    try {
      final tempDir = await getTemporaryDirectory();
      final folders = ['canvas_cache', 'album_arts'];
      for (var folder in folders) {
        final dir = Directory('${tempDir.path}/$folder');
        if (await dir.exists()) {
          final List<FileSystemEntity> files = dir.listSync();
          for (var file in files) {
            if (file is File) {
              try {
                await file.delete();
              } catch (_) {}
            }
          }
        }
      }
    } catch (_) {}
  }
}
